### ISSUE TITLE
Email notification: unable to verify the first certificate

### ISSUE THREAD

**Issue by pommetjehorlepiep** [Ravinou/borgwarehouse#367] opened 2024-12-08 07:43 UTC
Hi,

I'm getting the following error when trying to send Email notifications:

```
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1679:34)
    at TLSSocket.emit (node:events:518:28) 
    at TLSSocket._finishInit (node:_tls_wrap:1078:8)
    at ssl.onhandshakedone (node:_tls_wrap:864:12) {
  code: 'ESOCKET',
  command: 'CONN'
}
```

Running BorgWarehouse 2.4.1 in a Docker Container

Email config (using self-signed certificates):
```ini
MAIL_SMTP_FROM=borgwarehouse@<domain here>
MAIL_SMTP_HOST=<smtp server here>
MAIL_SMTP_PORT=587
MAIL_SMTP_LOGIN=<login here>
MAIL_SMTP_PWD=<pwd here>
MAIL_REJECT_SELFSIGNED_TLS=false
```
Installed the ca certificate for the domain in the container.

Update: 
... also tried using `MAIL_SMTP_PORT=25`, but got same error...

**Comment by Ravinou** [comment] 2024-12-26 10:37
This will be fixed in the next release in the next few days.

**Comment by Ravinou** [comment] 2024-12-26 16:58
I close it, but let me know if the problem is solve with v2.4.3, thank you.

**Closed by Ravinou** 2024-12-26 16:58 UTC
Labels: bug, next release

**Comment by pommetjehorlepiep** [comment] 2025-01-17 23:55
> This is fixed and will be in the next release in the next few days.

Sorry for the late response, but I can confirm issue has been fixed. Tested with v2.4.4.
