### ISSUE TITLE
Repositories are not created inside the repo path

### ISSUE THREAD

**Issue by fibrinogen** [Ravinou/borgwarehouse#318] opened 2024-10-03 09:57 UTC
Hi! Thank your for developung free software!

I'm running borgwarehouse on an ubuntu based distribution and installed as explained in side your "install on Debian" description. I'm starting borgwarehouse using pm2.

There is this repo directory inside the borgwarehouse home directory, but it is not used. After creating a repo inside GUI the path to the newly created repository is shown as 

ssh://borgwarehouse@localhost:22/./6514b9fc

and the repo is created directly inside the borgwarehouse users home directory. What am I doing wrong?

In adition I don't see log files written anywhere. There was no log directory created.

**Comment by Ravinou** [comment] 2024-10-05 13:42
Hi @fibrinogen !

> Hi! Thank your for developung free software!

Thank you to wrote this ! ❤️

> In adition I don't see log files written anywhere. There was no log directory created.

For the logs in a baremetal installation, [consult this please.](https://github.com/Ravinou/borgwarehouse/issues/287#issuecomment-2322968588)

>  I'm starting borgwarehouse using pm2.

I never use pm2, but I don't think this is the problem here.

> What am I doing wrong?

All the repositores will be in /home/borgwarehouse/repos/ directory. But it's normal that in your url path you don't see "repos/". Backup don't work for you after creating your repo inside BorgWarehouse ?

**Comment by fibrinogen** [comment] 2024-10-06 18:28
Backup works, but the the backup directory is not created inside the repos directory, but inside the borgwarehouse home directory.

The path to the repo is as follows inside the web UI: ssh://borgwarehouse@192.168.1.50:22/./6514b9fc
That does not creat the backup in /home/borgwarehouse/repos/6514b9fc
but in /home/borgwarehouse/6514b9fc

**Comment by Ravinou** [comment] 2024-10-06 19:13
Please, can you show me the content of your authorized_keys file ? Hide your public key. 

Thanks

**Comment by kotso** [comment] 2024-10-13 10:15
I have similar issue, running in docker (docker compose) my issue is that repo path contains `/./HASH` like: `ssh://borgwarehouse@server.com:2222/./a9922fbc` and if I try to use `ssh://borgwarehouse@server.com:2222/a9922fbc` as path I get error path not allowed. Only with `./` its working.

My authorized key looks good for me, here is example:

```
command="cd /home/borgwarehouse/repos;borg serve --restrict-to-path /home/borgwarehouse/repos/05bcc3ef --storage-quota 10G",restrict ssh-ed25519 KEY_CONTENT
```

**Comment by Ravinou** [comment] 2024-10-13 16:25
> I have similar issue, running in docker (docker compose) my issue is that repo path contains `/./HASH` like: `ssh://borgwarehouse@server.com:2222/./a9922fbc` and if I try to use `ssh://borgwarehouse@server.com:2222/a9922fbc` as path I get error path not allowed. Only with `./` its working.
> 
> My authorized key looks good for me, here is example:
> 
> ```
> command="cd /home/borgwarehouse/repos;borg serve --restrict-to-path /home/borgwarehouse/repos/05bcc3ef --storage-quota 10G",restrict ssh-ed25519 KEY_CONTENT
> ```

Hi @kotso. **The way it works is totally normal**. The behavior you're experiencing is expected and related to how borg and SSH handle paths when ` --restrict-to-path` is used. The `/./` in the path works because it helps borg resolve the repository's location relative to the current directory, as defined in your `authorized_keys` file.

Without `/./`, borg can't access the repository because the exact path is restricted in the `authorized_keys`. This means borg will only allow access to the specific path you defined, and it's more secure.

You can check the documentation of BorgBackup [here](https://borgbackup.readthedocs.io/en/stable/usage/general.html#repository-urls) and [here](https://borgbackup.readthedocs.io/en/stable/deployment/central-backup-server.html#restrictions) 👍

So keep using the syntax provided by the BorgWarehouse wizard, I designed it to make life easier.

**Comment by Ravinou** [comment] 2024-10-13 16:25
Any news [fibrinogen](https://github.com/fibrinogen) ?

**Comment by kotso** [comment] 2024-10-14 08:31
@Ravinou thank you!

**Comment by fibrinogen** [comment] 2024-10-27 12:57
Sorry for answering late. This is the content of the authorized_keys file:

command="cd /home/borgwarehouse/repos;borg serve --restrict-to-path /home/borgwarehouse/repos/6514b9fc --storage-quota 300G",restrict ssh-rsa

**Comment by Ravinou** [comment] 2024-11-02 08:53
The BorgBackup restriction is correct and your configuration seems fine too. I can't explain how it's possible for the folder to be in /home/borgwarehouse, there must be something I'm missing. Don't you have a particular mount, a symbolic link?
I'm definitely not reproducing your case and I need more information to help you.

What is your version of BorgBackup too? Thank you

**Comment by fibrinogen** [comment] 2024-11-03 19:09
Thank you very much for your support!
borgbackup 1.2.8

**Comment by fibrinogen** [comment] 2024-11-09 11:57
I think the issue was, that i tried to use a subdirectory inside the repos directory to use as backup root. No that I used the complete HD that I mounted as the repos directory it works as expected. Thank you.

**Comment by Ravinou** [comment] 2024-11-10 10:00
thanks for your feedback, it may help others in your installation situation.

**Closed by Ravinou** 2024-11-10 10:00 UTC
