### ISSUE TITLE
Error on repo.json with a large number of repo

### ISSUE THREAD

**Issue by YoSiJo** [Ravinou/borgwarehouse#34] opened 2023-04-03 13:04 UTC
I have recently started experiencing this problem.

```bash
borgwarehouse@borg:~/borgwarehouse$ /usr/bin/npm run start

> borgwarehouse@1.0 start
> next start

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/borgwarehouse/borgwarehouse/.env.local
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at handler (/home/borgwarehouse/borgwarehouse/.next/server/pages/api/repo.js:88:29)
    at async Object.apiResolver (/home/borgwarehouse/borgwarehouse/node_modules/next/dist/server/api-utils/node.js:372:9)
    at async NextNodeServer.runApi (/home/borgwarehouse/borgwarehouse/node_modules/next/dist/server/next-server.js:514:9)
    at async Object.fn (/home/borgwarehouse/borgwarehouse/node_modules/next/dist/server/next-server.js:828:35)
    at async Router.execute (/home/borgwarehouse/borgwarehouse/node_modules/next/dist/server/router.js:243:32)
    at async NextNodeServer.runImpl (/home/borgwarehouse/borgwarehouse/node_modules/next/dist/server/base-server.js:432:29)
    at async NextNodeServer.handleRequestImpl (/home/borgwarehouse/borgwarehouse/node_modules/next/dist/server/base-server.js:375:20)
    at async /home/borgwarehouse/borgwarehouse/node_modules/next/dist/server/base-server.js:157:99
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at handler (/home/borgwarehouse/borgwarehouse/.next/server/pages/api/repo.js:88:29)
    at async Object.apiResolver (/home/borgwarehouse/borgwarehouse/node_modules/next/dist/server/api-utils/node.js:372:9)
    at async NextNodeServer.runApi (/home/borgwarehouse/borgwarehouse/node_modules/next/dist/server/next-server.js:514:9)
    at async Object.fn (/home/borgwarehouse/borgwarehouse/node_modules/next/dist/server/next-server.js:828:35)
    at async Router.execute (/home/borgwarehouse/borgwarehouse/node_modules/next/dist/server/router.js:243:32)
    at async NextNodeServer.runImpl (/home/borgwarehouse/borgwarehouse/node_modules/next/dist/server/base-server.js:432:29)
    at async NextNodeServer.handleRequestImpl (/home/borgwarehouse/borgwarehouse/node_modules/next/dist/server/base-server.js:375:20)
    at async /home/borgwarehouse/borgwarehouse/node_modules/next/dist/server/base-server.js:157:99
^C
borgwarehouse@borg:~/borgwarehouse$ /home/borgwarehouse/borgwarehouse/helpers/shells/getStorageUsed.sh | jsonlint-php
Valid JSON (stdin)
borgwarehouse@borg:~/borgwarehouse$ cat /etc/debian_version 
11.6
borgwarehouse@borg:~/borgwarehouse$ node --version
v18.15.0
borgwarehouse@borg:~/borgwarehouse$ git status 
HEAD detached at v1.4.0
nothing to commit, working tree clean
```

I have overwritten the Sudoers file with the one from the Tag Branch, so far everything seems to work.

Currently I have no idea what the problem could be, if I have overlooked something or should check, please point it out.

**Comment by Ravinou** [comment] 2023-04-10 19:26
Hi @YoSiJo.
Does your application start?
Does the error occur during a specific action on BorgWarehouse please?

I will need to know more to try to help you 🙏

Thanks

**Comment by YoSiJo** [comment] 2023-04-11 17:03
The software seems to be running.

Web interface loads, but then gives an API Error.
Occurs on the first page and seems to be related to the Validirtem script above.

It also occurs with the cronjob for the software.
So the command 'http://localhost:3000/api/cronjob/getStorageUsed' triggers it as well.

I think it could be of interest that there are about 50+ repos now, one of which exceeds the limit of the last time. I think we are there in the one repo at now 500G+

**Comment by Ravinou** [comment] 2023-04-11 18:52
Can you please try this : 
- Stop your application (`systemctl stop borgwarehouse` if install as a service)
- Log to borgwarehouse user (`su borgwarehouse`)
- Launch the shell manually : 
```sh
cd /home/borgwarehouse/borgwarehouse/helpers/shells
./getStorageUsed.sh
```

You should get an output that looks like : 
```js
[{ size: 32, name: '10e73223' },  { size: 1155672, name: '83bd4ef1' }, { size: 112, name: '635a6f8b' }, { size: 32, name: 'bce68e87' }, { size: 44, name: 'e4c04552' }, ];
```

Do you get an output like this? How long does the command take to run ?

**Comment by YoSiJo** [comment] 2023-04-11 22:47
```bash
root@borg:~# systemctl stop borgwarehouse.service 
root@borg:~# su borgwarehouse
borgwarehouse@borg:/root$ cd /home/borgwarehouse/borgwarehouse/helpers/shells
borgwarehouse@borg:~/borgwarehouse/helpers/shells$ ./getStorageUsed.sh
[{"size": 851280, "name": "01f62bfe"}, {"size": 15633428, "name": "0dfb6f9c"}, {"size": 16, "name": "13cd3251"}, {"size": 6234216, "name": "16f83f9d"}, {"size": 4331260, "name": "19366eeb"}, {"size": 4539536, "name": "1a097e18"}, {"size": 4463764, "name": "1daaeb69"}, {"size": 1707948, "name": "20cddc90"}, {"size": 373184, "name": "22957099"}, {"size": 6591916, "name": "2348a486"}, {"size": 413624, "name": "25dc2271"}, {"size": 501557588, "name": "28f44f48"}, {"size": 1922312, "name": "2ca84398"}, {"size": 2582612, "name": "2cf18cf7"}, {"size": 13752292, "name": "3ba67ae7"}, {"size": 1460784, "name": "44558a5d"}, {"size": 29018660, "name": "45a4bb75"}, {"size": 34355476, "name": "4752f9f2"}, {"size": 1059884, "name": "4b50b66a"}, {"size": 11849952, "name": "4c181368"}, {"size": 2010256, "name": "4f012d16"}, {"size": 3642952, "name": "50bb5baa"}, {"size": 10428712, "name": "5734c14e"}, {"size": 23488244, "name": "5bad8d4b"}, {"size": 1091488, "name": "5be040d7"}, {"size": 8796128, "name": "601f91ee"}, {"size": 684760, "name": "60644ece"}, {"size": 22317224, "name": "6901fba6"}, {"size": 15682456, "name": "6b61b790"}, {"size": 764212, "name": "6d192086"}, {"size": 62744704, "name": "6f374f87"}, {"size": 1004824, "name": "6f8fbc42"}, {"size": 334360, "name": "71cb79bc"}, {"size": 17656128, "name": "727d5033"}, {"size": 3167648, "name": "733cb736"}, {"size": 4417732, "name": "760fa326"}, {"size": 848520, "name": "7a51004e"}, {"size": 35482740, "name": "7cc15b86"}, {"size": 3436052, "name": "7d21d4ac"}, {"size": 10115424, "name": "80faead5"}, {"size": 964656, "name": "83dec62a"}, {"size": 566676, "name": "83e66e80"}, {"size": 10737168, "name": "8b1743a2"}, {"size": 931970236, "name": "8bc98a36"}, {"size": 602204, "name": "914dbc24"}, {"size": 2431028, "name": "9ea0d9bd"}, {"size": 15532848, "name": "a115740d"}, {"size": 19192588, "name": "a4bc3cee"}, {"size": 16, "name": "a594f527"}, {"size": 611648, "name": "a59b689e"}, {"size": 16, "name": "aafae952"}, {"size": 2517936, "name": "abdd3fc6"}, {"size": 1358548, "name": "ad6d673b"}, {"size": 25689596, "name": "b67151ac"}, {"size": 12095080, "name": "b7dac26e"}, {"size": 16, "name": "ba225ed6"}, {"size": 23877464, "name": "be70b24a"}, {"size": 62166428, "name": "c6b67d47"}, {"size": 1963748, "name": "ccf17b93"}, {"size": 15636628, "name": "d3f3878a"}, {"size": 16188920, "name": "d590476c"}, {"size": 653540, "name": "d633ed50"}, {"size": 33479060, "name": "d9ff49e8"}, {"size": 16, "name": "e42eb082"}, {"size": 2588112, "name": "edb6ed18"}, {"size": 381052, "name": "f12355ad"}, {"size": 893808, "name": "fad5fd98"}]
borgwarehouse@borg:~/borgwarehouse/helpers/shells$ time ./getStorageUsed.sh
[{"size": 851280, "name": "01f62bfe"}, {"size": 15633428, "name": "0dfb6f9c"}, {"size": 16, "name": "13cd3251"}, {"size": 6234216, "name": "16f83f9d"}, {"size": 4331260, "name": "19366eeb"}, {"size": 4539536, "name": "1a097e18"}, {"size": 4463764, "name": "1daaeb69"}, {"size": 1707948, "name": "20cddc90"}, {"size": 373184, "name": "22957099"}, {"size": 6591916, "name": "2348a486"}, {"size": 413624, "name": "25dc2271"}, {"size": 501557588, "name": "28f44f48"}, {"size": 1922312, "name": "2ca84398"}, {"size": 2582612, "name": "2cf18cf7"}, {"size": 13752292, "name": "3ba67ae7"}, {"size": 1460784, "name": "44558a5d"}, {"size": 29018660, "name": "45a4bb75"}, {"size": 34355476, "name": "4752f9f2"}, {"size": 1059884, "name": "4b50b66a"}, {"size": 11849952, "name": "4c181368"}, {"size": 2010256, "name": "4f012d16"}, {"size": 3642952, "name": "50bb5baa"}, {"size": 10428712, "name": "5734c14e"}, {"size": 23488244, "name": "5bad8d4b"}, {"size": 1091488, "name": "5be040d7"}, {"size": 8796128, "name": "601f91ee"}, {"size": 684760, "name": "60644ece"}, {"size": 22317224, "name": "6901fba6"}, {"size": 15682456, "name": "6b61b790"}, {"size": 764212, "name": "6d192086"}, {"size": 62744704, "name": "6f374f87"}, {"size": 1004824, "name": "6f8fbc42"}, {"size": 334360, "name": "71cb79bc"}, {"size": 17656128, "name": "727d5033"}, {"size": 3167648, "name": "733cb736"}, {"size": 4417732, "name": "760fa326"}, {"size": 848520, "name": "7a51004e"}, {"size": 35482740, "name": "7cc15b86"}, {"size": 3436052, "name": "7d21d4ac"}, {"size": 10115424, "name": "80faead5"}, {"size": 964656, "name": "83dec62a"}, {"size": 566676, "name": "83e66e80"}, {"size": 10737168, "name": "8b1743a2"}, {"size": 931970236, "name": "8bc98a36"}, {"size": 602204, "name": "914dbc24"}, {"size": 2431028, "name": "9ea0d9bd"}, {"size": 15532848, "name": "a115740d"}, {"size": 19192588, "name": "a4bc3cee"}, {"size": 16, "name": "a594f527"}, {"size": 611648, "name": "a59b689e"}, {"size": 16, "name": "aafae952"}, {"size": 2517936, "name": "abdd3fc6"}, {"size": 1358548, "name": "ad6d673b"}, {"size": 25689596, "name": "b67151ac"}, {"size": 12095080, "name": "b7dac26e"}, {"size": 16, "name": "ba225ed6"}, {"size": 23877464, "name": "be70b24a"}, {"size": 62166428, "name": "c6b67d47"}, {"size": 1963748, "name": "ccf17b93"}, {"size": 15636628, "name": "d3f3878a"}, {"size": 16188920, "name": "d590476c"}, {"size": 653540, "name": "d633ed50"}, {"size": 33479060, "name": "d9ff49e8"}, {"size": 16, "name": "e42eb082"}, {"size": 2588112, "name": "edb6ed18"}, {"size": 381052, "name": "f12355ad"}, {"size": 893808, "name": "fad5fd98"}]

real    0m2.604s
user    0m0.142s
sys     0m0.689s
borgwarehouse@borg:~/borgwarehouse/helpers/shells$ ./getStorageUsed.sh | jsonlint-php
Valid JSON (stdin)
```

The first run was longer; ~20-30 second.
Only diff that i see is the `;` on the end. This is not exist by me.

**Comment by Ravinou** [comment] 2023-04-18 15:58
I keep trying to reproduce your problem without succeeding today :/. So I need more information.

Could you please confirm that your `/config/repo.json` file is a valid JSON ?

**Comment by YoSiJo** [comment] 2023-04-18 17:26
```bash
root@borg:~# cd /home/borgwarehouse/   
root@borg:/home/borgwarehouse# find . -iname "repo.json"
./borgwarehouse/config/repo.json
root@borg:/home/borgwarehouse# cat ./borgwarehouse/config/repo.json
root@borg:/home/borgwarehouse# file ./borgwarehouse/config/repo.json
./borgwarehouse/config/repo.json: empty
```

Nope, hmm. Bad. :(

Any idea how this could have happened?
The disk space has not run out.
And any idea how I can fix it?

**Comment by YoSiJo** [comment] 2023-05-27 17:37
# File system corrupted?

No this is not the case.

# Didn't you have a backup copy of this file?

Well, I had BorgBackup but also in all backup states before that the file is unfortunately empty. Except for the very first time where I had started borgwarehouse then and created a test repo.

# There were update problems

Not apparent.

# Other

I still have the question, how I can generate this file again.
I have also checked the permissions and everything looks fine.
I remembered that very early on when setting up the system, the disk space was full at some point. That would be a possible explanation, if thereby the filediscriptor was possibly broken.

**Comment by Ravinou** [comment] 2023-06-02 22:54
Hey @YoSiJo !
The `repo.json` file is created on the fly, so **I had to create a shell script for your specific case**.

Can you please [**read the description** and test it](https://github.com/Ravinou/borgwarehouse/blob/main/helpers/shells/recreateRepoConfigFile.sh) ?

For my part, I've tested my script on a server with about fifteen repositories and it works :)

**Comment by YoSiJo** [comment] 2023-06-07 06:56
Very big thanks. Working and fixed the file.
I had to take into account that it can't run under the borgwarehouse user, but needs root rights.

**Comment by Ravinou** [comment] 2023-06-09 19:46
Added to FAQ [just here](https://borgwarehouse.com/docs/help/faq/#rebuild-the-repojson-file). I close this issue now :)

**Closed by Ravinou** 2023-06-09 19:46 UTC
