### ISSUE TITLE
Enhance API to include the repo id in the answer when created a new repo

### ISSUE THREAD

**Issue by snapshotleisure** [Ravinou/borgwarehouse#322] opened 2024-10-14 13:16 UTC
Hi,

Love the project! its been great!, I am currently integration the API into my ansible script and it has been good. However I was wondering if its possible to add the repo name to the API call /api/repo/add?

Currently it just returns a message: success, it would be great if it could be something like:
{
  message: success
  repositoryName: 2e4e2138
}

That way I can get the repository name in one call. Currently the only way I can get the repository name after creating it is to get the list of repos and loop through to find the one with the same alias as the one I gave it.

Thank you!

**Comment by Ravinou** [comment] 2024-10-14 19:34
> Love the project! its been great!
Thank you so much to write this 😍

> However I was wondering if its possible to add the repo name to the API call /api/repo/add?
This request makes sense, and will be included in the next release, which will be available soon :)

**Comment by Ravinou** [comment] 2024-10-14 19:40
> So it is not a unique field and if someone was using the id = 0 for alias test and they deleted test and recreated a new repo test1, the id=0 is also assigned to test1, the api call will return test1 details. This may not be intended by the API Caller.

Can you explain or rephrase the question, I don't really understand the point ? 😄 

But I can confirm that the ID is simply an index and that the ID given will always be the smallest available. Giving an ID that has never been used would mean maintaining a rather useless database dedicated to this.

**Comment by snapshotleisure** [comment] 2024-10-14 23:03
> > So it is not a unique field and if someone was using the id = 0 for alias test and they deleted test and recreated a new repo test1, the id=0 is also assigned to test1, the api call will return test1 details. This may not be intended by the API Caller.
> 
> Can you explain or rephrase as a question, I don't really understand the point ? 😄
> 
> But I can confirm that the ID is simply an index and that the ID given will always be the smallest available. Giving an ID that has never been used would mean maintaining a rather useless database dedicated to this.

Haha yes, sorry! It was late at night and was getting tired, apologies for the incoherency!

For the Repo API, I noticed that the {id} used to query/update/delete a repo is based on the index and as you mentioned the ID is always the smallest available. 

The issue is that the ID could be used to reference 2 different repos at some stage, which a developer or API User may become unaware of. Example would be, API Consumer #1 created a repo with the following details:
{
  id: 0
  alias: This is the first repo
  repositoryName: 2e4e2138
}

API consumer #1 will save in the application the id=0, repoName: 2e4e2138 and if they query the API with /api/repo/id/0 it will return 200 OK, assuming that it is referencing repo **2e4e2138**

However, if someone (API Consumer #2) uses the API to delete ID = 0, and create it with /api/repo/add, the new repo will have the details:
{
  id: 0
  alias: This is the second repo
  repositoryName: 3e5e2140
}

API Consumer #1 is no unaware of the repo change and still assumes id=0 is 2e4e2138, because that is what is saved in their application and they use it in Borgmatic.

However because of API Consumer #2 deleting and creating a new repo, API Consumer #1 info is no longer correct. id=0 is equal to 3e5e2140. They will still get a 200 OK when making the query to /api/repo/id/0, but won't know why unless they do a check for the repositoryName to match. So this may lead to a situation where borgmatic is now failing as repo is gone, but their application still shows the repo is alive (but wrong repositoryName)

To avoid this kind of confusion and make the API more user friendly, I would like to suggest to change the API to use the repositoryName instead of the index as the ID field in the API.

This way when doing a query for the repository, it is always a unique field that is used. So the API call for Consumer #1 will instead look like: /api/repo/id/2e4e2138

and API Consumer #2 is: /api/repo/id/3e5e2140

The two consumers won't clash and can act in isolation.

Let me know if I still confusing, sorry it is hard to convey my thoughts sometimes.

Thank you!

**Comment by Ravinou** [comment] 2024-11-02 08:28
I understand perfectly and you're absolutely right. Historically, BorgWarehouse didn't work with this type of repository name but with an index system. Today this system doesn't make much sense, especially since the release of API control. However, removing it would be a major breaking change and a major code refactoring for me. 

I've just implemented the BATS tests, I still have other unit tests to implement and the transition to Typescript in the next few months. I want to finish this before releasing a version that incorporates a breaking change.

To avoid a breaking change for the moment, I think I'm going to make a second API that will allow you to delete/edit/read a repo with its name.

As your issue includes two requests, I'm going to close it and recreate two others for follow-up.

**Comment by Ravinou** [comment] 2024-11-02 08:53
The BorgBackup restriction is correct and your configuration seems fine too. I can't explain how it's possible for the folder to be in /home/borgwarehouse, there must be something I'm missing. Don't you have a particular mount, a symbolic link? 
I'm definitely not reproducing your case and I need more information to help you.

What is your version of BorgBackup too? Thank you

**Comment by snapshotleisure** [comment] 2024-11-06 10:52
Thank you for considering the enhancements and great work by the way!

**Comment by Ravinou** [comment] 2024-11-08 17:56
I re-open and I close it when it will be released ;)

**Closed** 2024-11-09 08:50 UTC
Labels: enhancement, next release

**Comment by Ravinou** [comment] 2024-12-26 17:13
The repository name in the creation API response is now include (v2.4.3)
