### ISSUE TITLE
ability to watch remote repos

### ISSUE THREAD

**Issue by fear** [Ravinou/borgwarehouse#23] opened 2023-02-24 15:45 UTC
Hey Ravinou, 

i just found jour project an it is is nearly exactly what i was looking for =D 

After installation i realized that the server isnt just a gui for the Monitoring, it is ment ro be run on the targetserver. Since Im storing to a hetzner stoage and im not able to run any software on that, is there a possibility to monitor the existing repos on the remote storage wit your web ui?

**Comment by Ravinou** [comment] 2023-02-25 14:18
Hi @fear :)
Indeed BorgWarehouse goes further than just displaying information about a repository. It is really used to manage a server and to report on it.

Your case is really precise, I don't know how Hetzner storage boxes work (even if it's my main hosting provider, and I have baremetal and VM with them) because I never tested them.

Do you know if these storage boxes are based on any standard ? 

I don't think it's impossible to add the case of a Hetzner storage box, even if it's not a small site I find the case interesting for BorgWarehouse.

**Comment by fear** [comment] 2023-02-25 18:31
Hey Ravinou, 

the hetzner Storage Boxes offer acces to the Storage via a secure shell on port 23. You can connect via console wich is offering a small set of tools: 

```
+-----------------------------------------------------------------------------+
| The following commands are available:                                       |
|   ls                                  list directory content                |
|   tree                                list directory content                |
|   cd                                  change current working directory      |
|   pwd                                 show current working directory        |
|   mkdir                               create new directory                  |
|   rmdir                               delete directory                      |
|   du                                  disk usage of files/directories       |
|   df                                  show disk usage                       |
|   dd                                  read and write files                  |
|   cat                                 output file content                   |
|   touch                               create new file                       |
|   cp                                  copy files/directories                |
|   rm                                  delete files/directories              |
|   unlink                              delete file/directory                 |
|   mv                                  move files/directories                |
|   chmod                               change file/directory permissions     |
|   md5|sha1|sha256|sha512              create hash sum of file               |
|   md5sum|sha1sum|sha256sum|sha512sum  create hash sum of file               |
|   head                                show first lines of file              |
|   tail                                show last lines of file               |
|   grep                                search for specific string in files   |
|   stat                                stat files/directory                  |
|                                                                             |
| Available as server side backend:                                           |
|   borg                                                                      |
|   rsync                                                                     |
|   scp                                                                       |
|   sftp                                                                      |
|   rclone serve restic --stdio                                               |
|                                                                             |
| Please note that this is only a restricted shell which do not               |
| support shell features like redirects or pipes.                             |
|                                                                             |
| You can find more information in our Docs:                                  |
|   https://docs.hetzner.com/robot/storage-box/                               |
+-----------------------------------------------------------------------------+
``` 

So i guess ists a chrooted linux envirnment with minimal toolset :)

beside that i could mount the storage to the borgwarehouse server as working directory via sftp, cifs or webdav. But in my opinion htis would be a workaround, since borg-hw. It would be greate to connect existing repositorys to the warehouse like [Add] ->  [new] || [existing] .

**Comment by fear** [comment] 2023-03-03 23:19
Thank you in advance 👍🏻

**Comment by Ravinou** [comment] 2023-03-21 09:31
Hi @fear, unfortunately hetzner storage boxes are not cloud products but products with a 30 day commitment. So it's more complicated for me to do integration tests of their product.

However I was wondering if you could try this:
- Create a new repository in borgwarehouse
- Get the username and the repo corresponding to the repository 
![image](https://user-images.githubusercontent.com/39600829/226566003-7e45019a-d5f2-4b19-8e34-9840a533d17d.png)
- Mount the storage box in SSHFS in the folder : `/var/borgwarehouse/USER/repos/REPOX/`
- Give the right user rights on the mount

If you can test this, I'm very interested, thanks for your help.

**Comment by Ravinou** [comment] 2023-04-18 16:00
Hi @fear , can you test it ? Thanks

**Comment by Flol0** [comment] 2023-05-16 07:07
Hi @Ravinou 
i think you are thinking too Complex in this.
He just wants to monitor Borg Repositorys hosted on Remote Servers. So you can also just use the normal Borg Commands to get information about the Remote Repository. 

Hope you understand what i mean.

**Comment by FelixSchwarz** [comment] 2024-01-18 12:53
@Ravinou I'm also interested in this and I can give you full access to storage box for some time (maybe 3-6 months, possibly longer). If BorgWarehouse supports Hetzner, I would deploy this for my own needs which means I can also spend time debugging issues and testing releases. You can find contact data in my Github profile.

**Comment by macinsight** [comment] 2024-03-11 14:44
I'd also appreciate if this could be tested and implement, as I am as well using Hetzners excellently priced storage boxes as targets for by BorgBackup stuff.

Addendum: A StorageBox of 1TB Size (the smallest) is only (I believe, I don't check my bills there) $3 or something similar a month.

**Comment by Ravinou** [comment] 2024-04-07 08:26
With the new BorgWarehouse v2 architecture, it's now easy to use a hetzner storage box for backup storage. [I tested it here today.](https://github.com/Ravinou/borgwarehouse/issues/196#issuecomment-2041362551)

**Comment by Ravinou** [comment] 2024-04-13 07:52
As several people have confirmed that it has worked properly since version 2.2.1, I'm closing this issue. Documentation for external storage [is available here](https://borgwarehouse.com/docs/admin-manual/external-storage/).

**Closed by Ravinou** 2024-04-13 07:52 UTC
Labels: enhancement
